require("basic-settings")
-- require("lazy")
require("plugins-setup")
require("colorscheme")
require("keymaps")
require("plugins.comment")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.nvim-cmp")

require("plugins.lsp.mason")
require("plugins.lsp.lspsaga")
require("plugins.lsp.lspconfig")
-- require("plugins.lsp.lspZero")

require("plugins.autopairs")
require("plugins.null-ls")
require("plugins.quick-scope")
require("plugins.colorizer")
require("plugins.vimtex")
require("plugins.whichKey")
-- require("plugins.indentLines")
require("autocommands")
-- require("plugins.tabbar")
require("plugins.undotree")
require("plugins.zenmode")
require("plugins.comment")
require("plugins.wilder-command-suggestions")
require("plugins.bufferline")
